/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.dobackaofront.lanchonete.view;

import br.com.dobackaofront.lanchonete.model.Lanche;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thami
 */
public class GUIMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIMenu.class.getName());
    private Iterable<Lanche> lanches;

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFramePesquisar = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisarPorNome = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPesquisarAcao = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPesquisarID = new javax.swing.JTextField();
        jButtonPesquisarConfirmar = new javax.swing.JButton();
        jButtonPesquisarCancelar = new javax.swing.JButton();
        jInternalFrameCadastroLanche = new javax.swing.JInternalFrame();
        jLabelCadastroLancheNome = new javax.swing.JLabel();
        jTextFieldCadastroLancheNome = new javax.swing.JTextField();
        jLabelCadastroLanchePreco = new javax.swing.JLabel();
        jTextFieldCadastroLanchePreco = new javax.swing.JTextField();
        jButtonCadastroLancheSalvar = new javax.swing.JButton();
        jButtonCadastroLancheCancelar = new javax.swing.JButton();
        jInternalFrameEditarCadastro = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEditarNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEditarPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEditarId = new javax.swing.JTextField();
        jButtonEditarSalvar = new javax.swing.JButton();
        jButtonEditarCancelar = new javax.swing.JButton();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroLanche = new javax.swing.JMenuItem();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItemPesquisarLanche = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jMenuItemVendasCarrinho = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lanchonete");

        jInternalFramePesquisar.setTitle("Pesquisar pelo Nome");
        jInternalFramePesquisar.setVisible(true);

        jTablePesquisarPorNome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePesquisarPorNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTablePesquisarPorNome);

        jLabel1.setText("Selecione a Ação Desejada:");

        jComboBoxPesquisarAcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editar", "Excluir" }));
        jComboBoxPesquisarAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPesquisarAcaoActionPerformed(evt);
            }
        });

        jLabel2.setText("Qual a ID do Lanche:");

        jButtonPesquisarConfirmar.setText("Confirmar");
        jButtonPesquisarConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarConfirmarActionPerformed(evt);
            }
        });

        jButtonPesquisarCancelar.setText("Cancelar");
        jButtonPesquisarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFramePesquisarLayout = new javax.swing.GroupLayout(jInternalFramePesquisar.getContentPane());
        jInternalFramePesquisar.getContentPane().setLayout(jInternalFramePesquisarLayout);
        jInternalFramePesquisarLayout.setHorizontalGroup(
            jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFramePesquisarLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jButtonPesquisarConfirmar)
                .addGap(18, 18, 18)
                .addComponent(jButtonPesquisarCancelar)
                .addGap(127, 127, 127))
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxPesquisarAcao, 0, 197, Short.MAX_VALUE)
                    .addComponent(jTextFieldPesquisarID))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFramePesquisarLayout.setVerticalGroup(
            jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPesquisarAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPesquisarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisarConfirmar)
                    .addComponent(jButtonPesquisarCancelar))
                .addGap(14, 14, 14))
        );

        jInternalFrameCadastroLanche.setTitle("Cadastro de Lanche");
        jInternalFrameCadastroLanche.setName(""); // NOI18N
        jInternalFrameCadastroLanche.setVisible(true);

        jLabelCadastroLancheNome.setText("Nome do Lanche:");

        jLabelCadastroLanchePreco.setText("Preço:");

        jTextFieldCadastroLanchePreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadastroLanchePrecoActionPerformed(evt);
            }
        });

        jButtonCadastroLancheSalvar.setText("Salvar");
        jButtonCadastroLancheSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroLancheSalvarActionPerformed(evt);
            }
        });

        jButtonCadastroLancheCancelar.setText("Cancelar");
        jButtonCadastroLancheCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroLancheCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCadastroLancheLayout = new javax.swing.GroupLayout(jInternalFrameCadastroLanche.getContentPane());
        jInternalFrameCadastroLanche.getContentPane().setLayout(jInternalFrameCadastroLancheLayout);
        jInternalFrameCadastroLancheLayout.setHorizontalGroup(
            jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCadastroLancheLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonCadastroLancheSalvar)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastroLancheCancelar)
                .addGap(100, 100, 100))
            .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastroLancheNome)
                    .addComponent(jLabelCadastroLanchePreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCadastroLancheNome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCadastroLanchePreco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jInternalFrameCadastroLancheLayout.setVerticalGroup(
            jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroLancheNome)
                    .addComponent(jTextFieldCadastroLancheNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroLanchePreco)
                    .addComponent(jTextFieldCadastroLanchePreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroLancheCancelar)
                    .addComponent(jButtonCadastroLancheSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFrameEditarCadastro.setTitle("Edição de Cadastro");
        jInternalFrameEditarCadastro.setVisible(true);

        jLabel3.setText("Nome do Lanche:");

        jTextFieldEditarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditarNomeActionPerformed(evt);
            }
        });

        jLabel4.setText("Preço:");

        jLabel5.setText("ID:");

        jTextFieldEditarId.setEnabled(false);

        jButtonEditarSalvar.setText("Salvar");
        jButtonEditarSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarSalvarActionPerformed(evt);
            }
        });

        jButtonEditarCancelar.setText("Cancelar");
        jButtonEditarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameEditarCadastroLayout = new javax.swing.GroupLayout(jInternalFrameEditarCadastro.getContentPane());
        jInternalFrameEditarCadastro.getContentPane().setLayout(jInternalFrameEditarCadastroLayout);
        jInternalFrameEditarCadastroLayout.setHorizontalGroup(
            jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                        .addComponent(jButtonEditarSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarCancelar))
                    .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldEditarNome)
                        .addComponent(jTextFieldEditarPreco)
                        .addComponent(jTextFieldEditarId, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jInternalFrameEditarCadastroLayout.setVerticalGroup(
            jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEditarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEditarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarSalvar)
                    .addComponent(jButtonEditarCancelar))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jInternalFramePesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jInternalFrameCadastroLanche, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jInternalFrameEditarCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameCadastroLanche)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(187, 187, 187)
                    .addComponent(jInternalFramePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(188, Short.MAX_VALUE)))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(187, 187, 187)
                    .addComponent(jInternalFrameEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(188, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameCadastroLanche, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(jInternalFramePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(121, Short.MAX_VALUE)))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(jInternalFrameEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(121, Short.MAX_VALUE)))
        );

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadastroLanche.setText("Lanche");
        jMenuItemCadastroLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroLancheActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroLanche);

        jMenuBarPrincipal.add(jMenuCadastro);

        jMenuPesquisar.setText("Pesquisar");

        jMenuItemPesquisarLanche.setText("Lanche");
        jMenuItemPesquisarLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarLancheActionPerformed(evt);
            }
        });
        jMenuPesquisar.add(jMenuItemPesquisarLanche);

        jMenuBarPrincipal.add(jMenuPesquisar);

        jMenuVendas.setText("Vendas");

        jMenuItemVendasCarrinho.setText("Carrinho");
        jMenuVendas.add(jMenuItemVendasCarrinho);

        jMenuBarPrincipal.add(jMenuVendas);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCadastroLanchePrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroLanchePrecoActionPerformed

    }//GEN-LAST:event_jTextFieldCadastroLanchePrecoActionPerformed

    private void jButtonCadastroLancheCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroLancheCancelarActionPerformed

        jTextFieldCadastroLancheNome.setText("");
        jTextFieldCadastroLanchePreco.setText("");
        jInternalFrameCadastroLanche.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroLancheCancelarActionPerformed

    private void jMenuItemCadastroLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroLancheActionPerformed
        jInternalFrameCadastroLanche.setVisible(true);                                                 
    }//GEN-LAST:event_jMenuItemCadastroLancheActionPerformed

    private void jButtonCadastroLancheSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroLancheSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldCadastroLancheNome.getText();
        
        if (nome.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O campo Nome do Lanche está vazio!");           
        } else {
            String preco = jTextFieldCadastroLanchePreco.getText();
            
            if (preco.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "O campo Preço está vazio!");
            } else {
                try {
                    double precoConvertido = Double.parseDouble(preco); 
                    Lanche lanche = new Lanche(nome,precoConvertido);
                    lanche.apresentarLanche();
                    lanche.salvar(nome, precoConvertido);
                                        
                    jTextFieldCadastroLancheNome.setText("");
                    jTextFieldCadastroLanchePreco.setText("");
                    
                    JOptionPane.showMessageDialog(rootPane, "O pedido " + nome + " foi cadastrado com Sucesso!");
                    
                    jInternalFrameCadastroLanche.setVisible(false);
                    
                } catch(Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Preencha o preço do lanche apenas com números separados por ponto!");
                }
            }
        }
    }//GEN-LAST:event_jButtonCadastroLancheSalvarActionPerformed

    private void jMenuItemPesquisarLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarLancheActionPerformed
        try {
            // TODO add your handling code here:
            String nome = JOptionPane.showInputDialog("Informe o Nome: ");
            Lanche lanche = new Lanche();
            ArrayList<Lanche> lanches = lanche.pesquisar(nome);
            
            
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("Nome");
            modelo.addColumn("Preço");
            
            for (Lanche lancheAux : lanches) {
                modelo.addRow(new Object[]{lancheAux.getId(), lancheAux.getNome(), lancheAux.getPreco()});
                jTablePesquisarPorNome.setModel(modelo);
            }
            
            jInternalFramePesquisar.setVisible(true);
        } catch (SQLException ex) {
            System.getLogger(GUIMenu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (IOException ex) {
            System.getLogger(GUIMenu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jMenuItemPesquisarLancheActionPerformed

    private void jComboBoxPesquisarAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPesquisarAcaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPesquisarAcaoActionPerformed

    private void jButtonPesquisarConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarConfirmarActionPerformed
        // TODO add your handling code here:
        Lanche lanche = new Lanche();
        String opcao = jComboBoxPesquisarAcao.getSelectedItem().toString();
        System.out.println("Opção selecionada: " + opcao);
        
        int idPesquisar = Integer.parseInt(jTextFieldPesquisarID.getText());
        System.out.println("ID Informado: " + idPesquisar);
        if (opcao.equals("Excluir")) {
            try {
                lanche.deletar(idPesquisar);
                JOptionPane.showMessageDialog(rootPane, "O Lanche de ID: " + idPesquisar + " foi excluído com Sucesso!");
            } catch (SQLException ex) {
                System.getLogger(GUIMenu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            } catch (IOException ex) {
                System.getLogger(GUIMenu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            
            jComboBoxPesquisarAcao.setSelectedIndex(0);
            jTextFieldPesquisarID.setText("");
            jInternalFramePesquisar.setVisible(false);
            
        } else { //editar
            jInternalFramePesquisar.setVisible(false);
            
            Lanche lancheRecuperado = null;
            try {
                lancheRecuperado = lanche.buscarPorId(idPesquisar);
            } catch (SQLException ex) {
                System.getLogger(GUIMenu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            } catch (IOException ex) {
                System.getLogger(GUIMenu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            
            jTextFieldEditarId.setText(idPesquisar + "");
            jTextFieldEditarNome.setText(lancheRecuperado.getNome());
            jTextFieldEditarPreco.setText(lancheRecuperado.getPreco() + "");
            
            
            jInternalFrameEditarCadastro.setVisible(true);
            
        }
    }//GEN-LAST:event_jButtonPesquisarConfirmarActionPerformed

    private void jButtonPesquisarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldPesquisarID.setText("");
        jComboBoxPesquisarAcao.setSelectedIndex(0);
        jInternalFramePesquisar.setVisible(false);
    }//GEN-LAST:event_jButtonPesquisarCancelarActionPerformed

    private void jTextFieldEditarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditarNomeActionPerformed

    private void jButtonEditarSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldEditarNome.getText();
        double preco = Double.parseDouble(jTextFieldEditarPreco.getText());
        int id = Integer.parseInt(jTextFieldEditarId.getText());
        
        Lanche lanche = new Lanche();
        try {
            lanche.editar(nome, preco, id);
        } catch (SQLException ex) {
            System.getLogger(GUIMenu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (IOException ex) {
            System.getLogger(GUIMenu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        jTextFieldEditarId.setText("");
        jTextFieldEditarNome.setText("");
        jTextFieldEditarPreco.setText("");
        
       JOptionPane.showMessageDialog(rootPane, "O Lanche foi Atualizado com Sucesso!");
        
        jInternalFrameEditarCadastro.setVisible(false);
        
    }//GEN-LAST:event_jButtonEditarSalvarActionPerformed

    private void jButtonEditarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldEditarId.setText("");
        jTextFieldEditarNome.setText("");
        jTextFieldEditarPreco.setText("");
        
        jInternalFrameEditarCadastro.setVisible(false);
    }//GEN-LAST:event_jButtonEditarCancelarActionPerformed

        public JInternalFrame getJInternalFrameEditarCadastro(){
            return jInternalFrameEditarCadastro;
        }
    /**
     * @param args the command line arguments
     */
   public JInternalFrame getJInternalFrameCadastroLanche() {
       return jInternalFrameCadastroLanche;
   }
   
   public JInternalFrame getjInternalFramePesquisar() {
       return jInternalFramePesquisar;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroLancheCancelar;
    private javax.swing.JButton jButtonCadastroLancheSalvar;
    private javax.swing.JButton jButtonEditarCancelar;
    private javax.swing.JButton jButtonEditarSalvar;
    private javax.swing.JButton jButtonPesquisarCancelar;
    private javax.swing.JButton jButtonPesquisarConfirmar;
    private javax.swing.JComboBox<String> jComboBoxPesquisarAcao;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrameCadastroLanche;
    private javax.swing.JInternalFrame jInternalFrameEditarCadastro;
    private javax.swing.JInternalFrame jInternalFramePesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCadastroLancheNome;
    private javax.swing.JLabel jLabelCadastroLanchePreco;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemCadastroLanche;
    private javax.swing.JMenuItem jMenuItemPesquisarLanche;
    private javax.swing.JMenuItem jMenuItemVendasCarrinho;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisarPorNome;
    private javax.swing.JTextField jTextFieldCadastroLancheNome;
    private javax.swing.JTextField jTextFieldCadastroLanchePreco;
    private javax.swing.JTextField jTextFieldEditarId;
    private javax.swing.JTextField jTextFieldEditarNome;
    private javax.swing.JTextField jTextFieldEditarPreco;
    private javax.swing.JTextField jTextFieldPesquisarID;
    // End of variables declaration//GEN-END:variables

    private static class jTable extends JTable {

        public jTable(DefaultTableModel modelo) {
        }
    }
}
